vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    housings_image:
      uri_prefix: /images/housings
      upload_destination: "%kernel.project_dir%/public/images/housings"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    cities_image:
      uri_prefix: /images/cities
      upload_destination: "%kernel.project_dir%/public/images/cities"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    regions_image:
      uri_prefix: /images/regions
      upload_destination: "%kernel.project_dir%/public/images/regions"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    quarters_image:
      uri_prefix: /images/quarters
      upload_destination: "%kernel.project_dir%/public/images/quarters"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
  #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
